credentials:
  usernames:
    jsmith:
      name: John Smith
      password: $2b$12$e6... # Use a hashed password here
    admin:
      name: Administrator
      password: $2b$12$a7...
cookie:
  name: some_cookie_name
  key: some_signature_key
  expiry_days: 30
